language: python

python:
  - 2.7
  - 3.6

env:
  - DJANGO=1.10
  - DJANGO=1.11

install:
  - pip install -r requirements.txt

script:
  - PYTHONPATH=. DJANGO_SETTINGS_MODULE=tests.test_settings django-admin test

notifications:
    email:
      - martyn@engage-sports.com

